version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-server-app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

  Install:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/verify_service.sh
      timeout: 300
      runas: ec2-user
